### ISSUE TITLE
Next, useQuery e monorepo

### ISSUE THREAD

**Issue by ayrtonlacerda** [ayrtonlacerda/saveissues#1]

**Comment by ayrtonlacerda** [comment]
https://github.com/TanStack/query/issues/3595#issuecomment-1504408143

**Comment by ayrtonlacerda** [comment]
### Error

```sh
 ⨯ ../src/QueryClientProvider.tsx (18:11) @ useQueryClient
 ⨯ Error: No QueryClient set, use QueryClientProvider to set one
    at useLoginMutation (../project-common/dist/services/auth/login.js:12:60)
    at Home (./src/app/auth/login/page.tsx:27:134)
digest: "2381507887"
  16 |
  17 |   if (!client) {
> 18 |     throw new Error('No QueryClient set, use QueryClientProvider to set one')
     |           ^
  19 |   }
  20 |
  21 |   return client
 GET /_next/static/chunks/app/auth/login/chunk-5WQ4PXEV.mjs.map 404 in 7436ms
 GET /auth/login 500 in 1627ms
```
### solution
>
> React-query V4 update:
> 
> ```ts
> webpack: (config, options) => {
>       if (options.isServer) {
>         config.externals = ['@tanstack/react-query', ...config.externals]
>       }
>       config.resolve.alias['@tanstack/react-query'] = path.resolve(
>         require.resolve('@tanstack/react-query'),
>         '../../../'
>       )
>       return config
>     }
> ```

This worked for us! But since our `next.config.js` is at the root, we didn't have to add the path traversing.

_Originally posted by @bombillazo in https://github.com/TanStack/query/issues/3595#issuecomment-1504408143_
